name: Build & Deploy to EC2

on:
  push:
    branches: [main]

concurrency:
  group: prod-deploy
  cancel-in-progress: true

env:
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/sase-backend
  IMAGE_LATEST: ghcr.io/${{ github.repository_owner }}/sase-backend:latest
  IMAGE_SHA: ghcr.io/${{ github.repository_owner }}/sase-backend:${{ github.sha }}
  BUILD_CONTEXT: .
  DOCKERFILE: ./Dockerfile

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (via GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (latest + sha) with cache
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.IMAGE_LATEST }}
            ${{ env.IMAGE_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull & Restart on EC2
        run: |
          ssh -o StrictHostKeyChecking=yes ubuntu@${{ secrets.EC2_HOST }} '
            # if your GHCR package is private, keep this login:
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || true
            cd /opt/app &&
            docker compose pull &&
            docker compose up -d &&
            docker image prune -f
          '
